name: Javascript Execution


on: workflow_dispatch

jobs:
  build:
    runs-on: [ self-hosted ]
    
    steps:
     - uses: actions/checkout@v2
       name: Clone project
       
     - name: install mocha
       run: |
        npm install --save-dev mocha
    
     - name: run the tests
       run: | 
        npm run test
